### ISSUE TITLE
Feature request - tweet / re-tweet / answer

### ISSUE THREAD

**Issue by snakers4** [nurtdinovadf/tweetsender#1]
- Add original tweet / re-tweet / answer label to the 
-- first line of the email

**Comment by snakers4** [comment]
@nurtdinovadf 
Also it may be a consequence of last tweet_id log error (i.e. last tweet being logged incorrectly), but it is difficult to see order in which tweets were tweeted 
[example](http://prntscr.com/i20dda)

**Comment by nurtdinovadf** [comment]
@snakers4 I filtered out all the replies (there's a switch, so it could be turned on), retweets have their own subject (email subject) now, and the url is that of original tweet, is it acceptable?

**Comment by snakers4** [comment]
Sounds ok, I guess commit and close?

**Comment by nurtdinovadf** [comment]
ok
